name: Lean Action CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up olean cache
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: oleans

      - name: Configure
        working-directory: src/lean4
        run: |
          lake exe cache get
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Lean (elan)
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          source $HOME/.elan/env
        
      - name: Build the lean project
        run: |
          source $HOME/.elan/env
          pushd src/lean4 && lake build > lean4_build.log && popd
      
      - name: Run Score Summarization Script
        run: |
          source $HOME/.elan/env
          python src/scripts/score_solution.py
